In [3]:
import numpy as np


Generación edades

In [8]:
edades = np.random.uniform(
    size = (3, 3),
    low = 20,
    high = 50
)
edades = np.around(edades)
edades

array([[23., 45., 42.],
       [39., 31., 29.],
       [49., 26., 35.]])

Generación ingresos

In [9]:
ingresos = np.random.uniform(
    size = (3, 3),
    low = 2000,
    high = 5000
)
ingresos = np.around(ingresos)
ingresos

array([[4514., 3241., 3054.],
       [4210., 2514., 2387.],
       [4050., 4424., 3108.]])

Unir data

In [36]:
reshape_edades = edades.reshape(9)
reshape_ingresos = ingresos.reshape(9)

edades_ingresos = np.column_stack((reshape_edades, reshape_ingresos))
display(
    edades_ingresos,
    edades_ingresos.shape
)

array([[  23., 4514.],
       [  45., 3241.],
       [  42., 3054.],
       [  39., 4210.],
       [  31., 2514.],
       [  29., 2387.],
       [  49., 4050.],
       [  26., 4424.],
       [  35., 3108.]])

(9, 2)

Filtrar datos entre [20,  30] años y [2000, 5000] de ingresos

In [63]:
min_edades_permitidas = reshape_edades >= 20
max_edades_permitidas = reshape_edades <= 30
edades_permitidas = np.logical_and(min_edades_permitidas, max_edades_permitidas)

display(
    reshape_edades,
    edades_permitidas,
    reshape_edades[edades_permitidas]
)

array([23., 45., 42., 39., 31., 29., 49., 26., 35.])

array([ True, False, False, False, False,  True, False,  True, False])

array([23., 29., 26.])

Filtrar datos entre [2000, 5000] de ingresos

In [64]:
min_ingresos_permitidos = reshape_ingresos >= 2000
max_ingresos_permitidos = reshape_ingresos <= 5000
ingresos_permitidos = np.logical_and(min_ingresos_permitidos, max_ingresos_permitidos)

display(
    reshape_ingresos,
    ingresos_permitidos,
    reshape_ingresos[ingresos_permitidos]
)

array([4514., 3241., 3054., 4210., 2514., 2387., 4050., 4424., 3108.])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

array([4514., 3241., 3054., 4210., 2514., 2387., 4050., 4424., 3108.])

AND lógico para cumplir ambas condiciones

In [65]:
permitidos = np.logical_and(edades_permitidas, ingresos_permitidos)
display(permitidos)

array([ True, False, False, False, False,  True, False,  True, False])

Obtener datos del arreglo original donde se cumplan las condiciones anteriores

In [67]:
edades_ingresos_permitidos = edades_ingresos[permitidos]

display(
    edades_ingresos,
    edades_ingresos_permitidos
)

array([[  23., 4514.],
       [  45., 3241.],
       [  42., 3054.],
       [  39., 4210.],
       [  31., 2514.],
       [  29., 2387.],
       [  49., 4050.],
       [  26., 4424.],
       [  35., 3108.]])

array([[  23., 4514.],
       [  29., 2387.],
       [  26., 4424.]])